Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryCS.Data;
using LibraryCS.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;



namespace LibraryCS.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryContext _context;
        private IHostingEnvironment _appEnvironment;
        //private readonly IWebHostEnviroment _webHostEnviroment;

        public BooksController(LibraryContext context,IHostingEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        // GET: Books
        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber,
            int? pageSize)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["BookIDSortParm"] = String.IsNullOrEmpty(sortOrder) ? "BookID_desc" : "";
            ViewData["NameBookSortParm"] = sortOrder == "NameBook" ? "NameBook_desc" : "NameBook";
            ViewData["AuthorSortParm"] = sortOrder == "Author" ? "Author_desc" : "Author";
            ViewData["DescriptionSortParm"] = sortOrder == "Description" ? "Description_desc" : "Description";
            ViewData["EditionSortParm"] = sortOrder == "Edition" ? "Edition_desc" : "Edition";
            ViewData["GenreSortParm"] = sortOrder == "Genre" ? "Genre_desc" : "Genre";
            ViewData["AviabilitySortParm"] = sortOrder == "Aviability" ? "Aviability_desc" : "Aviability";
            ViewData["DateSortParm"] = sortOrder == "BookAddDate" ? "BookAddDate_desc" : "BookAddDate";

            if (searchString!=null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            ViewData["PageSize"] = pageSize;

            var books = from b in _context.Books
                       select b;

            if(!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(b => b.NameBook.Contains(searchString)
                ||b.Author.Contains(searchString)
                || b.Description.Contains(searchString)
                || b.Edition.Contains(searchString)
                || b.Genre.Contains(searchString)
                || b.BookID.ToString().Contains(searchString)
                || b.BookAddDate.ToString().Contains(searchString)
                );
            }

            if (String.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "BookID";
            }
            bool descending = false;

            if (sortOrder.EndsWith("_desc"))
            {
                sortOrder = sortOrder.Substring(0, sortOrder.Length - 5);
                descending = true;
            }

            if (descending)
            {
                books = books.OrderByDescending(b => EF.Property<object>(b, sortOrder));
            }
            else
            {
                books = books.OrderBy(b => EF.Property<object>(b, sortOrder));
            }

            return View(await PaginatedList<Book>.CreateAsync(books.AsNoTracking(),pageNumber ?? 1,pageSize ?? 5));
        }
       

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(p=>p.Pictures)
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NameBook,Author,Description,Edition,Genre,BookAddDate")] Book book)
        {
            
            if (ModelState.IsValid)
            {
                book.Aviability = true;
                book.BookPicturesPath = "/Files/noimage.png";
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookID,NameBook,Author,Description,Edition,Genre,Aviability,BookAddDate,BookPicturesPath")] Book book)
        {
            if (id != book.BookID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books
                .Include(p => p.Pictures)
                .FirstOrDefaultAsync(m => m.BookID == id);

            foreach (PictureModel picture in book.Pictures)
            {
                _context.Pictures.Remove(picture);
            }
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookID == id);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryCS.Data;
using LibraryCS.Models;
using Microsoft.AspNetCore.Authorization;

namespace LibraryCS.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly LibraryContext _context;
        public bool IsAdmin => HttpContext.User.HasClaim("IsAdmin", bool.TrueString);

        //public bool IsAdmin => HttpContext.User.Identity.IsAuthenticated;
        
        public OrdersController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var orders = _context.Orders.Include(o => o.Book).Include(o => o.Reader);
            return View(await orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Book)
                .Include(o => o.Reader)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            if (!IsAdmin)
            {
                return Forbid();
            }
            BookAviableDropDownList();
            ViewData["ReaderID"] = new SelectList(_context.Readers, "ID", "FullName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,BookID,ReaderID,OrderDate,OrderReturnDate")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                var book = await _context.Books.FindAsync(order.BookID);
                book.Aviability = false;
                _context.Update(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookID"] = new SelectList(_context.Books, "BookID", "BookID", order.BookID);
            ViewData["ReaderID"] = new SelectList(_context.Readers, "ID", "ID", order.ReaderID);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!IsAdmin)
            {
                return Forbid();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            BookAviableDropDownList();
            ViewData["ReaderID"] = new SelectList(_context.Readers, "ID", "FullName", order.ReaderID);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,BookID,ReaderID,OrderDate,OrderReturnDate")] Order order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookID"] = new SelectList(_context.Books, "BookID", "BookID", order.BookID);
            ViewData["ReaderID"] = new SelectList(_context.Readers, "ID", "ID", order.ReaderID);
            return View(order);
        }

        public IActionResult CloseOrderList()
        {
            if (!IsAdmin)
            {
                return Forbid();
            }

            var orderQuery = from o in _context.Orders.Include(o => o.Book).Include(o => o.Reader)
                                 orderby o.OrderID
                                 where o.OrderReturnDate == null
                                 select o;
                return View(orderQuery.ToList());
        }
        public async Task<IActionResult> CloseOrder(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!IsAdmin)
            {
                return Forbid();
            }

            var order = await _context.Orders.Include(o => o.Book).Include(o => o.Reader).FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Close
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CloseOrder([Bind("OrderID,BookID,ReaderID,OrderDate,OrderReturnDate")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Update(order);
               await _context.SaveChangesAsync();
                var book = await _context.Books.FindAsync(order.BookID);
                book.Aviability = true;
                _context.Update(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!IsAdmin)
            {
                return Forbid();
            }

            var order = await _context.Orders
                .Include(o => o.Book)
                .Include(o => o.Reader)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            
            // возвращаем книгу только если удаляем активный заказ 
            if (order.OrderReturnDate==null)
            {
                var book = await _context.Books.FindAsync(order.BookID);
                book.Aviability = true;
                _context.Update(book);
                await _context.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderID == id);
        }
        private void BookAviableDropDownList()
        {
            var booksQuery = from b in _context.Books
                             orderby b.BookID
                             where b.Aviability != false
                             select b;
            ViewData["BookID"] = new SelectList(booksQuery.AsNoTracking(), "BookID", "FullName");
        }
        private void BookNotAviableDropDownList()
        {
            var booksQuery = from b in _context.Books
                             orderby b.BookID
                             where b.Aviability == false
                             select b;
            ViewData["BookID"] = new SelectList(booksQuery.AsNoTracking(), "BookID", "FullName");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library CS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryCS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pictures" asp-action="Index">Files</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Readers" asp-action="Index">Readers</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"  >Orders</a>
                            <div class="dropdown-menu bg-dark text-light" aria-labelledby="navbarDropDown">
                                <a class="dropdown-item bg-dark text-light" asp-controller="Orders" asp-action="Create">Add Order</a>
                                <a class="dropdown-item bg-dark text-light" asp-controller="Orders" asp-action="CloseOrderList">Close Order</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item bg-success text-light" asp-controller="Orders" asp-action="Index">View all</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Accounts">Admin page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    &copy; 2020 - Library CS -
                </div>
                </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>