Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryCS.Models
{
    public class Book
    {
        public int BookID { get; set; }
        [Required]
        public string NameBook { get; set; }
        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-' ''.']*$")]
        public string Author { get; set; }
        public string Description { get; set; }
        public string Edition { get; set; }
        public string Genre { get; set; }

        public bool Aviability { get; set; }
        public string BookPicturesPath { get; set; }

        [DataType(DataType.Date)]
        public DateTime BookAddDate { get; set; }
        public ICollection<Order> Order { get; set; }

        public List<PictureModel> Pictures { get; set; } = new List<PictureModel>();

        public string FullName
        {
            get
            {
                return BookID + "--" + Author + "--" + NameBook;
            }
        }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryCS.Data;
using LibraryCS.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;



namespace LibraryCS.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryContext _context;
        private IHostingEnvironment _appEnvironment;
        //private readonly IWebHostEnviroment _webHostEnviroment;

        public BooksController(LibraryContext context,IHostingEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        // GET: Books
        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber,
            int? pageSize)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["BookIDSortParm"] = String.IsNullOrEmpty(sortOrder) ? "BookID_desc" : "";
            ViewData["NameBookSortParm"] = sortOrder == "NameBook" ? "NameBook_desc" : "NameBook";
            ViewData["AuthorSortParm"] = sortOrder == "Author" ? "Author_desc" : "Author";
            ViewData["DescriptionSortParm"] = sortOrder == "Description" ? "Description_desc" : "Description";
            ViewData["EditionSortParm"] = sortOrder == "Edition" ? "Edition_desc" : "Edition";
            ViewData["GenreSortParm"] = sortOrder == "Genre" ? "Genre_desc" : "Genre";
            ViewData["AviabilitySortParm"] = sortOrder == "Aviability" ? "Aviability_desc" : "Aviability";
            ViewData["DateSortParm"] = sortOrder == "BookAddDate" ? "BookAddDate_desc" : "BookAddDate";

            if (searchString!=null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            ViewData["PageSize"] = pageSize;

            var books = from b in _context.Books
                       select b;

            if(!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(b => b.NameBook.Contains(searchString)
                ||b.Author.Contains(searchString)
                || b.Description.Contains(searchString)
                || b.Edition.Contains(searchString)
                || b.Genre.Contains(searchString)
                || b.BookID.ToString().Contains(searchString)
                || b.BookAddDate.ToString().Contains(searchString)
                );
            }

            if (String.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "BookID";
            }
            bool descending = false;

            if (sortOrder.EndsWith("_desc"))
            {
                sortOrder = sortOrder.Substring(0, sortOrder.Length - 5);
                descending = true;
            }

            if (descending)
            {
                books = books.OrderByDescending(b => EF.Property<object>(b, sortOrder));
            }
            else
            {
                books = books.OrderBy(b => EF.Property<object>(b, sortOrder));
            }

            return View(await PaginatedList<Book>.CreateAsync(books.AsNoTracking(),pageNumber ?? 1,pageSize ?? 5));
        }
       

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(p=>p.Pictures)
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NameBook,Author,Description,Edition,Genre,BookAddDate")] Book book)
        {
            
            if (ModelState.IsValid)
            {
                book.Aviability = true;
                book.BookPicturesPath = "/Files/noimage.png";
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookID,NameBook,Author,Description,Edition,Genre,Aviability,BookAddDate,BookPicturesPath")] Book book)
        {
            if (id != book.BookID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books
                .Include(p => p.Pictures)
                .FirstOrDefaultAsync(m => m.BookID == id);

            foreach (PictureModel picture in book.Pictures)
            {
                _context.Pictures.Remove(picture);
            }
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookID == id);
        }
    }
}

Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LibraryCS.Data;
using LibraryCS.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryCS.Controllers
{
    public class PicturesController : Controller
    {
        private readonly LibraryContext _context;
        private IHostingEnvironment _appEnvironment;

        public PicturesController(LibraryContext context, IHostingEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }
        public IActionResult Index()
        {
            return View(_context.Pictures.ToList());
        }
        [HttpPost]
        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                PictureModel picture = new PictureModel { Name = uploadedFile.FileName, Path = path };
                _context.Pictures.Add(picture);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddFileToBook(int? id, IFormFile uploadedFile)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                PictureModel picture = new PictureModel { Name = uploadedFile.FileName, Path = path };
                _context.Pictures.Add(picture);
                _context.SaveChanges();
                var book = await _context.Books
                .FirstOrDefaultAsync(b => b.BookID == id);
                book.BookPicturesPath = picture.Path;
                _context.Books.Update(book);
                _context.SaveChanges();
            }
            return Redirect(("/Books/Details/"+id.ToString()));
        }
        public async Task<IActionResult> AddFileToReader(int? id, IFormFile uploadedFile)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                PictureModel picture = new PictureModel { Name = uploadedFile.FileName, Path = path };
                _context.Pictures.Add(picture);
                _context.SaveChanges();
                var reader = await _context.Readers
                .FirstOrDefaultAsync(r => r.ID == id);
                reader.ReadersPicsPath = picture.Path;
                _context.Readers.Update(reader);
                _context.SaveChanges();
            }
            return Redirect(("/Readers/Details/" + id.ToString()));
        }

        public async Task<IActionResult> AddPictureToBook(int? id, IFormFile uploadedFile)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                PictureModel picture = new PictureModel { Name = uploadedFile.FileName, Path = path };
                var book = await _context.Books
                .FirstOrDefaultAsync(b => b.BookID == id);
                book.Pictures.Add(picture);
                _context.Books.Update(book);
                _context.SaveChanges();
            }
            return Redirect(("/Books/Details/" + id.ToString()));
        }
        // GET: Files/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Pictures
                .FirstOrDefaultAsync(m => m.Id == id);
            if (file == null)
            {
                return NotFound();
            }
            return View(file);
        }

        // GET: File/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Pictures
                .FirstOrDefaultAsync(m => m.Id == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // POST: File/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var file = await _context.Pictures.FindAsync(id);
            _context.Pictures.Remove(file);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Books/Create.cshtml
@model LibraryCS.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить Книгу</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameBook" class="control-label"></label>
                <input asp-for="NameBook" class="form-control" />
                <span asp-validation-for="NameBook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edition" class="control-label"></label>
                <input asp-for="Edition" class="form-control" />
                <span asp-validation-for="Edition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookAddDate" class="control-label"></label>
                <input asp-for="BookAddDate" class="form-control" />
                <span asp-validation-for="BookAddDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" /> |
                <a asp-action="Index" class="btn btn-secondary">Отмена</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Books/Delete.cshtml
@model LibraryCS.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Удалить книгу</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Html.DisplayFor(item => item.FullName)</h4>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NameBook)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NameBook)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Edition)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Edition)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Aviability)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Aviability)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BookAddDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BookAddDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="BookID" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary"> Отмена</a>
    </form>
</div>

Views/Books/Details.cshtml
@model LibraryCS.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Детальная информация</h1>
<h2>@Html.DisplayFor(item => item.FullName)</h2>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NameBook)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NameBook)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Edition)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Edition)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Aviability)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Aviability)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BookAddDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BookAddDate)
        </dd>
    </dl>
</div>
@if (User.HasClaim("IsAdmin", bool.TrueString))
{
    <p>
        @foreach (var f in Model.Pictures)
        {
            <img src="@Url.Content(f.Path)">
            <a asp-action="Delete" asp-route-id="@f.Id" asp-controller="Pictures">Удалить</a>
        }
    </p>
}

@if ((User.Identity.IsAuthenticated==false || User.HasClaim("IsAdmin", bool.FalseString)) && Model.Pictures != null)
{
    <div class="container m-3">
        <div class="row">
            <div class="col-6">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100 h-100" src="@Url.Content(Model.Pictures.LastOrDefault().Path)" alt="Первый слайд">
                        </div>
                        @for (int i = 0; i < Model.Pictures.Count - 1; i++)
                        {
                            <div class="carousel-item">
                                <img class="d-block w-100 h-100" src="@Url.Content(Model.Pictures[i].Path)" alt="@Url.Content(Model.Pictures[i].Name)">
                            </div>

                        }
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
}
@if (User.HasClaim("IsAdmin", bool.TrueString))
{
    <div>

        <form asp-action="AddPictureToBook" asp-route-id="@Model.BookID" asp-controller="Pictures" method="post" enctype="multipart/form-data">
            <input type="file" name="uploadedFile" /><br>
            <input type="submit" value="Add Picture to Book" />
        </form>
    </div>
    <p></p>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.BookID" class="btn btn-danger">Изменить</a> |
        <a asp-action="Index" class="btn btn-secondary">Отмена</a>
    </div>
}

Views/Books/Edit.cshtml
@model LibraryCS.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Изменить книгу</h1>

<h2>@Html.DisplayFor(item => item.FullName)</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookID" />
            <input type="hidden" asp-for="BookPicturesPath" />
            <div class="form-group">
                <label asp-for="NameBook" class="control-label"></label>
                <input asp-for="NameBook" class="form-control" />
                <span asp-validation-for="NameBook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edition" class="control-label"></label>
                <input asp-for="Edition" class="form-control" />
                <span asp-validation-for="Edition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aviability" /> @Html.DisplayNameFor(model => model.Aviability)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="BookAddDate" class="control-label"></label>
                <input asp-for="BookAddDate" class="form-control" />
                <span asp-validation-for="BookAddDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" /> |
                <a asp-action="Index" class="btn btn-secondary">Отмена</a>
            </div>

        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Books/Files.cshtml
@model IEnumerable<LibraryCS.Models.FileModel>
@{
    ViewData["Title"] = "Добавление файла";
}
<h3>Выберите файл для загрузки</h3>
<form asp-action="AddFile" asp-controller="Books" method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile" /><br>
    <input type="submit" value="Загрузить" />
</form>

<h3>Все файлы</h3>
@foreach (var f in Model)
{
    <p><img src="@Url.Content(f.Path)"></p>
}

Views/Books/Index.cshtml
@using LibraryCS.Data;
@model PaginatedList<LibraryCS.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Книги</h1>

<p>
    <a asp-action="Create">Добавить новую книгу</a>

</p>

<form asp-action="Index" method="get" asp-route-pageSize="2">
    <div class="form-actions no-color">
        <p>
            Find: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" asp-route-pageSize="2"/> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>


<p>
    Количество книг на странице:

    <a asp-action="Index" class="btn" asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="2">2</a>
    <a asp-action="Index" class="btn" asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="4">4</a>
    <a asp-action="Index" class="btn" asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="6">6</a>
    <a asp-action="Index" class="btn" asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="12">12</a>
</p>



<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["BookIDSortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]">ID</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameBookSortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]">NameBook</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["AuthorSortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]"> Author </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DescriptionSortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]">Description</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["EditionSortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]">Edition</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["GenreSortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]">Genre</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["AviabilitySortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]">Aviability</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-pageSize="@ViewData["PageSize"]" asp-route-currentFilter="@ViewData["currentFilter"]">DateSort</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameBook)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aviability)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookAddDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BookID">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.BookID">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.BookID">Удалить</a>
            </td>
        </tr>
        }
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageSize="@ViewData["PageSize"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageSize="@ViewData["PageSize"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>

Views/Books/Pictures.cshtml
@model IEnumerable<LibraryCS.Models.PictureModel>
@{
    ViewData["Title"] = "Добавление файла";
}
<h3>Выберите файл для загрузки</h3>
<form asp-action="AddFile" asp-controller="Books" method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile" /><br>
    <input type="submit" value="Загрузить" />
</form>

<h3>Все файлы</h3>
@foreach (var f in Model)
{
    <p><img src="@Url.Content(f.Path)"></p>
}