Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LibraryCS.Data;
using LibraryCS.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryCS.Controllers
{
    public class FilesController : Controller
    {
        private readonly LibraryContext _context;
        private IHostingEnvironment _appEnvironment;

        public FilesController(LibraryContext context, IHostingEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }
        public IActionResult Index()
        {
            return View(_context.Files.ToList());
        }
        [HttpPost]
        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                FileModel file = new FileModel { Name = uploadedFile.FileName, Path = path };
                _context.Files.Add(file);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddFileToBook(int? id, IFormFile uploadedFile)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                FileModel file = new FileModel { Name = uploadedFile.FileName, Path = path };
                _context.Files.Add(file);
                _context.SaveChanges();
                var book = await _context.Books
                .FirstOrDefaultAsync(b => b.BookID == id);
                book.BookPicturesPath = file.Path;
                _context.Books.Update(book);
                _context.SaveChanges();
            }
            return Redirect(("/Books/Details/"+id.ToString()));
        }
        public async Task<IActionResult> AddFileToReader(int? id, IFormFile uploadedFile)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                FileModel file = new FileModel { Name = uploadedFile.FileName, Path = path };
                _context.Files.Add(file);
                _context.SaveChanges();
                var reader = await _context.Readers
                .FirstOrDefaultAsync(r => r.ID == id);
                reader.ReadersPicsPath = file.Path;
                _context.Readers.Update(reader);
                _context.SaveChanges();
            }
            return Redirect(("/Readers/Details/" + id.ToString()));
        }
        // GET: Files/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .FirstOrDefaultAsync(m => m.Id == id);
            if (file == null)
            {
                return NotFound();
            }
            return View(file);
        }

        // GET: File/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .FirstOrDefaultAsync(m => m.Id == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // POST: File/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var file = await _context.Files.FindAsync(id);
            _context.Files.Remove(file);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Files/Delete.cshtml
@model LibraryCS.Models.FileModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Are you sure you want to delete this?</h1>
<h2>@Html.DisplayFor(item => item.Name)</h2>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
    </dl>
</div>
<div>
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Удалить" class="btn btn-danger" /> |
    <a asp-action="Index" class="btn btn-secondary"> Отмена</a>
</form>
</div>

Views/Files/Details.cshtml
@model LibraryCS.Models.FileModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Детальная информация</h1>
<h2>@Html.DisplayFor(item => item.Name)</h2>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>       
    </dl>
</div>
<div>
    <a asp-action="Delete" asp-route-id="@Model.Id"class="btn btn-danger" >Удалить</a> |
    <a asp-action="Index"class="btn btn-secondary">Отмена</a>
</div>

Views/Files/Index.cshtml
@model IEnumerable<LibraryCS.Models.FileModel>
@{
    ViewData["Title"] = "Добавление файла";
}
<h3>Выберите файл для загрузки</h3>
<form asp-action="AddFile" asp-controller="Files" method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile" /><br>
    <input type="submit" value="Загрузить" />
</form>

<h3>Все файлы</h3>
@foreach (var f in Model)
{
<div>
    <p><img src="@Url.Content(f.Path)"></p>

        <a asp-action="Details" asp-route-id="@f.Id">Детали</a> |
        <a asp-action="Delete" asp-route-id="@f.Id">Удалить</a>
</div>
        }